title: test title
author: jd git
email: jd@domainmail.com
description: > # this means to ignore newlines until "baseurl:"
 awesome description

# social links
twitter_username: jd110029 # DO NOT include the @ character, or else the build will fail!
github_username:  jdgit110029 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
